version: '3.3'

services:
  database:
    container_name: database
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    ports:
     - 3306:3306
    environment:
      - MYSQL_DATABASE=cms
      - MYSQL_ROOT_PASSWORD=testcms
    networks:
      - cms

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 80:80
    
    
networks:
  cms:
    name: cms
    driver: bridge